// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsV8VZeeQ9qfV2-SRC3f5tGDNN10WtfXM',
    appId: '1:766749314350:web:bcf3be1ab7b285576bbebf',
    messagingSenderId: '766749314350',
    projectId: 'deardiary-9dfc3',
    authDomain: 'deardiary-9dfc3.firebaseapp.com',
    storageBucket: 'deardiary-9dfc3.appspot.com',
    measurementId: 'G-0FLK8VFM3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxKrEq-EJVwkn8i51Rq0WV3y8khjO2gTQ',
    appId: '1:766749314350:android:d8c4ec036fff7af36bbebf',
    messagingSenderId: '766749314350',
    projectId: 'deardiary-9dfc3',
    storageBucket: 'deardiary-9dfc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1cYyjfXxo0OU2Yr_iX-LVWX4xL7-n8Q',
    appId: '1:766749314350:ios:a7dcc2c206360ffc6bbebf',
    messagingSenderId: '766749314350',
    projectId: 'deardiary-9dfc3',
    storageBucket: 'deardiary-9dfc3.appspot.com',
    iosClientId: '766749314350-auk30scjud5jvjdg3g760cvt6ioqrlil.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp',
  );
}
